plugins {
    id 'java-library'
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

dependencies {
    annotationProcessor(libs.service.annotations)
    configurations.compileClasspath.extendsFrom(configurations.annotationProcessor)
    testAnnotationProcessor(libs.service.annotations)
}

test {
    useJUnitPlatform()
}
