plugins {
    id 'java-library'
}

tasks.withType(JavaCompile).configureEach {
    options.release = 21
}

dependencies {
    configurations.compileClasspath.extendsFrom(configurations.annotationProcessor)
    annotationProcessor(libs.lookup)
    testAnnotationProcessor(libs.lookup)
}

test {
    useJUnitPlatform()
}
