import com.pswidersk.gradle.python.VenvTask

plugins {
    id 'regi-headless.deps-conventions'
    id 'regi-headless.java-conventions'
    id 'com.pswidersk.python-plugin' version '3.2.16'
}

dependencies {
    implementation(libs.bundles.serversuite)
    implementation(libs.jython.standalone)
    implementation(libs.args4j)
    implementation(libs.bundles.regi)
    implementation(libs.bundles.regi) {artifact {extension = "jar"}}
    implementation(libs.bundles.regi.tools)
    implementation(libs.bundles.regi.tools) {artifact {extension = "jar"} }
    runtimeOnly(libs.hec.cwms.ratings.cda)

    testImplementation(libs.bundles.junit.api)
    testRuntimeOnly(libs.bundles.junit.engine)
}

configurations.configureEach {
    exclude group: 'mil.army.usace.hec', module: 'hec-cwmsvue'
    exclude group: 'mil.army.usace.hec', module: 'hec-gt-crs'
    exclude group: 'org.openjfx', module: '*'
    exclude group: 'mil.army.usace.hec.swingx', module: '*'
    exclude group: 'org.swinglabs', module: '*'
    exclude group: 'org.jfree', module: '*'
    exclude group: 'org.netbeans.modules', module: '*'
    exclude group: 'org.netbeans.api', module: '*'
    exclude group: 'mil.army.usace.hec.map', module: 'hec-osmmap'
    exclude group: 'mil.army.usace.hec', module: 'hec-geojson'
    exclude group: 'mil.army.usace.hec', module: 'dssplugin-excel'
    exclude group: 'mil.army.usace.hec', module: 'dssgui'
    exclude group: 'com.fifesoft', module: 'rstaui'
    exclude group: 'mil.army.usace.hec', module: 'rma-javafx-core'
    exclude group: 'mil.army.usace.hec', module: 'hec-vrt-io'
    exclude group: 'org.apache.xmlgraphics', module: '*'
    exclude group: 'org.apache.poi', module: '*'
    exclude group: 'javax.media', module: '*'
    exclude group: 'com.vividsolutions', module: 'jts'
}

jar {
    manifest {
        attributes('Implementation-Version': project.version)
    }
}

pythonPlugin {
    pythonVersion = "3.11.15"
    condaVersion = "26.3.2-2"
    condaInstaller = "Miniforge3"
    installDir = file(layout.buildDirectory.dir("python"))
}

tasks.register('installPythonBuildTools', VenvTask) {
    group = 'build setup'
    description = 'Installs Python packages needed to build the wheel.'

    venvExec = 'pip'
    args = ['install', '--upgrade', 'pip', 'build']
}

tasks.register('buildPythonWheel', VenvTask) {
    group = "distribution"
    description = "Builds a Python .whl file using the Gradle-managed Python environment."

    dependsOn bundlePython
    dependsOn installPythonBuildTools

    workingDir = file("${buildDir}/install/regi-python")
    venvExec = "python"
    args = ["-m", "build", "--wheel"]

    doLast {
        println "Python Wheel built in: ${workingDir}/dist"
    }
}

tasks.register('bundlePython', Sync) {
    description = 'Bundles Python scripts and creates the java_lib directory'
    into "${buildDir}/install/regi-python/"

    from('src/main/python') {
        include 'pyproject.toml'
        filter { line -> line.replaceAll('@VERSION@', project.version.toString()) }
    }

    from('src/main/python') {
        exclude 'pyproject.toml'
    }

    into('regi-python/lib') {
        from configurations.runtimeClasspath
        from jar.archiveFile
        exclude "**/*.nbm"
    }
}

tasks.register('testPythonWheel') {
    group = 'verification'
    description = 'Creates a venv, installs the wheel, and runs a test script.'
    dependsOn buildPythonWheel

    doLast {
        def venvName = "test_venv"
        def wheelDir = "${projectDir}/build/install/regi-headless/dist"
        def testScript = "src\\test\\resources\\usace\\rowcps\\headless\\examples\\GateFlowCalc2_Jpype.py"

        // 1. Create VENV if it doesn't exist
        exec {
            commandLine 'cmd', '/c', "python -m venv ${venvName}"
        }

        // 2. Install Wheel and Run Script
        // We chain these using '&&' so they run in the same shell session where the venv is active
        exec {
            workingDir projectDir
            def wheelFile = fileTree(dir: wheelDir, include: '*.whl').singleFile.absolutePath
            def venvActivate = file("${venvName}/Scripts/activate.bat").absolutePath
            environment 'CDA_URL', project.findProperty('CDA_URL') ?: ""
            environment 'API_KEY', project.findProperty('API_KEY') ?: ""
            environment 'OFFICE_ID', project.findProperty('OFFICE_ID') ?: ""
            environment 'JAVA_HOME', System.getProperty('java.home')
            commandLine 'cmd', '/c', "\"${venvActivate}\" && pip install --force-reinstall \"${wheelFile}\" && python -u  ${testScript}"
            standardOutput = System.out
            errorOutput = System.err
        }
    }
}
