plugins {
    id 'regi-headless.deps-conventions'
    id 'regi-headless.java-conventions'
}

dependencies {
    implementation(libs.bundles.serversuite)
    implementation(libs.jython.standalone)
    implementation(libs.args4j)
    implementation(libs.bundles.regi)
    implementation(libs.bundles.regi) {artifact {extension = "jar"}}
    implementation(libs.bundles.regi.tools)
    implementation(libs.bundles.regi.tools) {artifact {extension = "jar"} }
    implementation(libs.otel)
    runtimeOnly(libs.hec.cwms.ratings.cda)

    testImplementation(libs.bundles.junit.api)
    testRuntimeOnly(libs.bundles.junit.engine)
}

configurations.configureEach {
    exclude group: 'mil.army.usace.hec', module: 'hec-cwmsvue'
    exclude group: 'mil.army.usace.hec', module: 'hec-gt-crs'
    exclude group: 'org.openjfx', module: '*'
    exclude group: 'mil.army.usace.hec.swingx', module: '*'
    exclude group: 'org.swinglabs', module: '*'
    exclude group: 'org.jfree', module: '*'
}

jar {
    manifest {
        attributes('Implementation-Version': project.version)
    }
}

test {
    useJUnitPlatform()
}
