[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "regi-python"
version = "@VERSION@"
description = "USACE REGI Python Bridge"
dependencies = [
    "JPype1>=1.4.1",
]

[tool.setuptools]
packages = ["regi_python"]

[tool.setuptools.package-data]
"regi_python" = ["lib/*.jar"]