[versions]

# HEC Dependencies
service-annotations = "2.1.0"
hec-server-suite = "8.4.5"

# REGI Dependencies
regi-tools = "9.1.1"
regi = "3.5.0-alpha001"

# Third Party
jython-standalone = "2.7.2"
args4j = "2.32"

# Test
junit = "6.1.0"

[libraries]
# HEC Dependencies
service-annotations = { module = "mil.army.usace.hec:service-annotations", version.ref = "service-annotations" }
serversuite = { module = "mil.army.usace.hec:hec-server-suite", version.ref = "hec-server-suite" }
serversuite-cda = { module = "mil.army.usace.hec:cda-server-suite", version.ref = "hec-server-suite" }
serversuite-jdbc = { module = "mil.army.usace.hec:jdbc-server-suite", version.ref = "hec-server-suite" }
hec-db-cda = { module = "mil.army.usace.hec:hec-db-cda", version = "14.1.0" }
hec-cwms-ratings-cda = { module = "mil.army.usace.hec:hec-cwms-ratings-io-cda", version = "4.2.2"}

# REGI Dependencies
regi-computation = {module = "mil.army.wmist.regi:computation", version.ref = "regi"}

# Regi-tools Dependencies
regi-tools-regi-core = {module = "mil.army.wmist.regi-tools:regi-core", version.ref = "regi-tools"}
regi-tools-regi-data = {module = "mil.army.wmist.regi-tools:regi-data", version.ref = "regi-tools"}
regi-tools-regi-dao = {module = "mil.army.wmist.regi-tools:regi-dao", version.ref = "regi-tools"}
regi-tools-regi-cwms = {module = "mil.army.wmist.regi-tools:regi-cwms", version.ref = "regi-tools"}

# Third Party
jython-standalone = {module = "org.python:jython-standalone", version.ref = "jython-standalone"}
args4j = {module = "args4j:args4j", version.ref = "args4j"}

# Test
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }

[bundles]
regi = ["regi-computation"]
regi-tools = [
    "regi-tools-regi-core",
    "regi-tools-regi-cwms",
    "regi-tools-regi-dao",
    "regi-tools-regi-data"
]
serversuite = ["serversuite", "serversuite-cda", "serversuite-jdbc", "hec-db-cda"]

junit-api = ["junit-jupiter-api", "junit-jupiter-params"]
junit-engine = ["junit-jupiter-engine", "junit-platform-launcher"]